# -*- coding: utf-8 -*-
"""Assignment11week11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzyAGJKmC40EhTr8CFH9WzR1fQwxx50Y
"""

import json
import re
from flask import Flask, flash
from flask import render_template
from flask import redirect
from flask import url_for
from flask import request

app = Flask(__name__)
app.secret_key = 'f3cfe9ed8fae309f02079dbf';
with open('outputfile.json') as file:
    todolist = json.load(file)


@app.route('/')
def home():
    todo=todolist
    return render_template('index.html',todolist=todo)


@app.route("/submit",methods=["post"])
def submit():
    errors=[] 
    email=request.form['email']
    task=request.form['task']
    priority=request.form['priority']
    input_priority=['low','medium', 'high']
    email_regex='^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$'
    if not (re.search(email_regex,email)): 
        errors.append('Invalid Email')
    
    if priority not in input_priority: 
        errors.append('Invalid Priority')

    if len(errors)>0:
        for i in errors:
            flash(i)
        return redirect(url_for('home'))
    else:
        dictionary=dict()
        if len(todolist)>0:
            dictionary["id"] = todolist[len(todolist)-1]["id"]+1
        else:
            dictionary["id"] = 1
        dictionary["task"]=task
        dictionary["email"]=email
        dictionary["priority"]=priority
        todolist.append(dictionary)

        return redirect(url_for('home'))

@app.route("/delete/<id>")
def delete(id):
    for x in range(0,len(todolist)):
        if todolist[x]["id"]==int(id):
            todolist.pop(x)             
    return redirect(url_for('home'))

@app.route("/clear", methods=["post"])
def clear():
    todolist.clear()
    return redirect(url_for('home'))

@app.route("/save")
def save():
    with open('outputfile.json', 'w') as fout:
        json.dump(todolist, fout)
    flash("Your To do tasks have been saved")
    return redirect(url_for('home'))

if __name__ == '__main__':
    app.run(debug=True)